### PR TITLE
Python 3 support

### LINKED ISSUE #6: python 3 support
Can we have python 3 support

### PR DESCRIPTION
**Pull request by ThaWeatherman**
Fixes #6

### CODE REVIEW

**Comment by ThaWeatherman** [comment]
Note that all tests pass in 3 and 2.

**Comment by ThaWeatherman** [comment]
@achillean is this ever going to get merged? all tests pass in both 2 and 3.

**Comment by achillean** [comment]
Yes! Sorry for the delay, reviewing/ testing the code right now.

**Comment by achillean** [comment]
A few comments:

1. Amazing code cleanup and work to make it compatible w/ Python3. Definitely a huge improvement over the old code - thank you!

2. The WebAPIError and the WebAPI class will eventually be deprecated (everything in api.py) in the near future but they should be kept around until a major version change.

3. I should add more tests around the new streaming capabilities and modify the tests to check whether the API key has elevated privileges: if it does run an additional set of tests that check advanced filters/ paging/ etc.

Thank you again for the work and I apologize for the late response!

Best regards,

-John

**Comment by ThaWeatherman** [comment]
No worries! Just glad it got merged in. Hopefully users will find it useful.

**Pull request merged**
