### PR TITLE
Point the repo directly

### PR DESCRIPTION
**Pull request by fabaff**

### CODE REVIEW

**Comment by achillean** [comment]
Thank you for the submission but is there a reason to point to the /tree/master location instead of just keeping the typical frontpage URL?

**Comment by wagner-certat** [comment]
@fabaff Are you planning to adapt your PR for only the protocol change?

**Comment by fabaff** [comment]
> @fabaff Are you planning to adapt your PR for only the protocol change?

There is no other branch than master. Thus I don't get what the benefit is of pointing to `/tree/master`. 

I have adjusted the URL in the specification of the Fedora RPM back then when it was introduced. This change would avoid that other people have to do the same when they create a package for a distribution or perform other tasks using the details from PyPI or the setup.py file like release-monitoring.org, etc.

**Comment by wagner-certat** [comment]
Just for clarification: I also think that https://github.com/achillean/shodan-python is the more correct URL

**Review by sebix — APPROVED** [review]

**Pull request merged**
